### ISSUE TITLE
Parameter

### ISSUE THREAD

**Issue by dowitsch** [puzzle/svn2git#1]
Parameter werden nicht korrekt eingelesen.

Mit dem Aufruf: ./svn2git.bash --project=beispiel --svn=svn://svn.test.ch/test/test/ --git=git@ssh.gitlab.test.ch:svn/test.git

erhalte ich folgenden Error:

svn2git.bash: option '--svn' doesn't allow an argument
svn2git.bash: option '--git' doesn't allow an argument

mit short-hand flags habe ich folgender Fehler:

./svn2git.bash: line 209: GIT_REPOSITORY: GIT_REPOSITORY is required

Da werden die Variablen falsch gesetzt, zum Beispiel wird $SVN_REPOSITORY auf  "--svn" gesetzt.

**Comment by srotman** [comment]
Should be fixed on master now
